apiVersion: v1
kind: Pod
metadata:
  name: nvidia-smi
spec:
  # nodeSelector:
  #   nvidia.com/gpu.present: "true"
  runtimeClassName: nvidia
  restartPolicy: Never
  containers:
    - name: nvidia-smi
      image: nvcr.io/nvidia/cuda:12.5.0-base-ubuntu22.04
      command: ["nvidia-smi"]
      resources:
        limits:
          nvidia.com/gpu: "1"
